
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programCCOMILLAS COLON COMMA CSTRING DATA_TYPE DIVIDE EQUAL EQUAL_EQUAL EQUAL_GREATER_THAN EQUAL_LESS_THAN EXCLAMATION FIMPORT FLOAT FUNCTION_TYPE GREATER_THAN ID IMPORT INTEGER LBRACE LBRACKET LESS_THAN LOGIC LPAREN MAIN MINUS MINUS_MINUS NOEQUAL PERIOD PLUS PLUS_PLUS QUESTION RBRACE RBRACKET RESERVED RETURN RPAREN SEMICOLON SSTRING STATIC TIMESprogram : inicioinicio : RESERVED RESERVED ID LBRACE mas RBRACEmas : code\n                | code mascode : RESERVED STATIC FUNCTION_TYPE MAIN LPAREN args RPAREN LBRACE pp RBRACEpp : ppsargs : cd\n                | cd argscd : DATA_TYPE LBRACKET RBRACKET RESERVEDpps : RESERVED PERIOD RESERVED PERIOD RESERVED LPAREN CCOMILLAS RPAREN SEMICOLONempty :'
    
_lr_action_items = {'RESERVED':([0,3,6,9,22,23,28,29,31,],[3,4,7,7,24,27,30,-5,32,]),'$end':([1,2,11,],[0,-1,-2,]),'ID':([4,],[5,]),'LBRACE':([5,19,],[6,22,]),'STATIC':([7,],[10,]),'RBRACE':([8,9,12,25,26,29,36,],[11,-3,-4,29,-6,-5,-10,]),'FUNCTION_TYPE':([10,],[13,]),'MAIN':([13,],[14,]),'LPAREN':([14,32,],[15,33,]),'DATA_TYPE':([15,17,27,],[18,18,-9,]),'RPAREN':([16,17,20,27,34,],[19,-7,-8,-9,35,]),'LBRACKET':([18,],[21,]),'RBRACKET':([21,],[23,]),'PERIOD':([24,30,],[28,31,]),'CCOMILLAS':([33,],[34,]),'SEMICOLON':([35,],[36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'inicio':([0,],[2,]),'mas':([6,9,],[8,12,]),'code':([6,9,],[9,9,]),'args':([15,17,],[16,20,]),'cd':([15,17,],[17,17,]),'pp':([22,],[25,]),'pps':([22,],[26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> inicio','program',1,'p_program','analizert.py',13),
  ('inicio -> RESERVED RESERVED ID LBRACE mas RBRACE','inicio',6,'p_inicio','analizert.py',17),
  ('mas -> code','mas',1,'p_mas','analizert.py',22),
  ('mas -> code mas','mas',2,'p_mas','analizert.py',23),
  ('code -> RESERVED STATIC FUNCTION_TYPE MAIN LPAREN args RPAREN LBRACE pp RBRACE','code',10,'p_segundo','analizert.py',30),
  ('pp -> pps','pp',1,'p_pp','analizert.py',34),
  ('args -> cd','args',1,'p_args','analizert.py',40),
  ('args -> cd args','args',2,'p_args','analizert.py',41),
  ('cd -> DATA_TYPE LBRACKET RBRACKET RESERVED','cd',4,'p_argumento','analizert.py',48),
  ('pps -> RESERVED PERIOD RESERVED PERIOD RESERVED LPAREN CCOMILLAS RPAREN SEMICOLON','pps',9,'p_imp','analizert.py',52),
  ('empty -> <empty>','empty',0,'p_empty','analizert.py',57),
]
